server:
  tomcat:
    uri-encoding: utf-8
  compression:
    enabled: true
spring:
  profiles:
    active: dev

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    banner-mode: console